# Generated by Django 5.0.2 on 2024-06-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_etablissement_url_fichier_alter_etat_date_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='banque',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='url_fichier',
            field=models.CharField(max_length=150),
        ),
    ]
